logging:
  level:
    sql: DEBUG
    web: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        messaging: DEBUG
    es:
      unizar:
        mii:
          tmdad:
            chatapp: DEBUG

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    url: "jdbc:postgresql://db:5432/chatapp?createDatabaseIfNotExist=true"
    driver-class-name: "org.postgresql.Driver"
    username: "chatapp"
    password: "chatapp"
  rabbitmq-amqp:
    ssl: false
    host: "rabbitmq"
    port: 5672
    user: "guest"
    password: "guest"
    vhost: "/"
  rabbitmq-http:
    ssl: false
    host: "rabbitmq"
    port: 15672
    user: "guest"
    password: "guest"
    vhost: "/"
  config:
    activate:
      on-profile: "dev"