logging:
  level:
    root: WARN

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    user: "guest"
    password: "guest"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

