logging:
  level:
    root: WARN

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: off
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    url: "jdbc:postgresql://db:5432/chatapp?createDatabaseIfNotExist=true"
    driver-class-name: "org.postgresql.Driver"
    username: "chatapp"
    password: "chatapp"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  rabbitmq-amqp:
    ssl: true
    host: "kangaroo.rmq.cloudamqp.com"
    port: 5671
    user: "myhiscii"
    password: "yTd4qvT9B9N7cpSdS6Vyh_x9aYUabsWv"
    vhost: "myhiscii"
  rabbitmq-http:
    ssl: true
    host: "kangaroo.rmq.cloudamqp.com"
    port: 443
    user: "myhiscii"
    password: "yTd4qvT9B9N7cpSdS6Vyh_x9aYUabsWv"
    vhost: "myhiscii"

